Repository kubearchive/kubearchive, pull requests merged in 2024-09, with the labels that each got.

#360 Add core resources endpoints
  cmd/api/main.go
  cmd/api/routers/routers.go
  cmd/api/routers/routers_test.go
  pkg/database/database.go
  pkg/database/database_test.go
  pkg/database/fake/database_generated.go
  pkg/database/fake/database_generated_test.go
Labels: kind/feature, component/api

#367 Add metrics and Grafana stack
  DEVELOPMENT.md
  charts/kubearchive/conf/grafana-otelcol-config.yaml
  charts/kubearchive/conf/kubearchive-otelcol-config.yaml
  charts/kubearchive/templates/_helpers.tpl
  charts/kubearchive/templates/observability/grafana-lgtm-stack.yaml
  charts/kubearchive/templates/observability/otel-collector.yaml
  charts/kubearchive/templates/traces-collector.yaml
  go.mod
  go.sum
  pkg/observability/trace.go
Labels: kind/feature, area/metrics

#369 Fix envvar for cache expiration
  charts/kubearchive/templates/api_server/api_server.yaml
  cmd/api/main.go
  test/integration/integration_test.go
Labels: kind/bug, component/api

#328 Release as single YAML
  .github/workflows/release.yml
  DEVELOPMENT.md
  charts/kubearchive/templates/_helpers.tpl
  charts/kubearchive/templates/api_server/api_server.yaml
  charts/kubearchive/templates/api_server/role_binding.yaml
  charts/kubearchive/templates/api_server/service_account.yaml
  charts/kubearchive/templates/certificates.yaml
  charts/kubearchive/templates/database/database.yaml
  charts/kubearchive/templates/database/database_secret.yaml
  charts/kubearchive/templates/namespace.yaml
  charts/kubearchive/templates/sink/sink.yaml
  charts/kubearchive/templates/test/kac.yaml
  charts/kubearchive/templates/test/namespace.yaml
  charts/kubearchive/templates/test/test-sa.yaml
  charts/kubearchive/values.yaml
  cmd/operator/generate.sh
  database/init_db.go
  docs/modules/ROOT/pages/contributors/release.adoc
  hack/install-database.sh
  hack/quick-install.sh
  hack/release.sh
  test/integration/integration_test.go
Labels: kind/feature, area/release

#374 Add observability documentation
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/configuration/enable-observability.adoc
Labels: kind/documentation, area/metrics

#366 Add 'unparam' to Go linters
  .golangci.yml
Labels: kind/feature, area/ci

#346 Create SQL script to initialize the database
  DEVELOPMENT.md
  database/ddl-resource.sql
  database/ddl.sql
  database/init_db.go
  hack/install-database.sh
  hack/release.sh
Labels: area/database

#378 Add installation docs
  charts/kubearchive/templates/api_server/api_server.yaml
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/getting-started/installation.adoc
Labels: kind/documentation

#387 Fix documentation workflow to publish tags
  .github/workflows/documentation-build.yaml
  .github/workflows/documentation-release.yaml
Labels: kind/documentation

#389 Fix POSTGRES_URL env value in helm chart templates
  charts/kubearchive/templates/_helpers.tpl
Labels: kind/bug

#392 Change Fixes to Resolves
  .github/pull_request_template.md
Labels: kind/feature

#391 Fix error of function not found in DDL
  database/ddl-resource.sql
Labels: kind/bug

#398 Add namespace support to the CLI
  pkg/cmd/get.go
  pkg/cmd/get_test.go
Labels: kind/feature, component/cli

#395 Introduce telemetry modes
  charts/kubearchive/templates/_helpers.tpl
  docs/modules/ROOT/pages/configuration/enable-observability.adoc
  pkg/observability/trace.go
Labels: kind/feature, area/metrics

#401 Extract DB deployment from helm chart
  DEVELOPMENT.md
  charts/kubearchive/templates/_helpers.tpl
  charts/kubearchive/templates/api_server/api_server.yaml
  charts/kubearchive/templates/database/database.yaml
  charts/kubearchive/templates/database/database_secret.yaml
  charts/kubearchive/templates/sink/sink.yaml
  charts/kubearchive/values.yaml
  hack/quick-install.sh
  integrations/database/postgresql/install.sh
  integrations/database/postgresql/k8s-resources.yaml
Labels: kind/feature

#429 Move the test SA to the test namespace
  DEVELOPMENT.md
  charts/kubearchive/templates/test/test-sa.yaml
  charts/kubearchive/values.yaml
Labels: kind/bug

#434 Fix POSTGRES_PORT in the database secret
  charts/kubearchive/templates/database/database_secret.yaml
Labels: kind/bug

#436 Pass proper context to DB Ping
  cmd/api/routers/routers.go
Labels: kind/bug

#427 Cache discovery endpoint calls
  cmd/api/discovery/apiresources.go
  cmd/api/discovery/apiresources_test.go
  cmd/api/main.go
  cmd/api/routers/routers.go
  cmd/api/routers/routers_test.go
Labels: kind/feature, component/api, area/performance

#422 Release uses deploy SSH key
  .github/workflows/release.yml
  docs/modules/ROOT/pages/contributors/secret-rotation.adoc
Labels: kind/feature, area/release

#426 sink can archive objects when they are deleted
  cmd/sink/filters/filters.go
  cmd/sink/main.go
Labels: kind/feature, component/sink

#456 Add kubearchive test user yaml resources
  DEVELOPMENT.md
  test/users/test-user.yaml
Labels: kind/feature, area/deployment
