Repository kubearchive/kubearchive, pull requests merged in 2024-07, with the labels that each got.

#178 Fix how to get kind from resource name
  DEVELOPMENT.md
  cmd/api/abort/abort.go
  cmd/api/auth/authn.go
  cmd/api/auth/authz.go
  cmd/api/discovery/apiresources.go
  cmd/api/discovery/apiresources_test.go
  cmd/api/main.go
  cmd/api/main_test.go
  cmd/api/routers/routers.go
  cmd/api/routers/routers_test.go
Labels: kind/bug

#200 Add 'go mod tidy' job
  .github/workflows/static_code_analysis.yml
  go.sum
Labels: kind/feature

#188 update database test data
  database/resource.sql
Labels: kind/bug

#212 Add .editorconfig file
  .editorconfig
  DEVELOPMENT.md
  charts/kubearchive/README.md
  database/README.md
Labels: kind/feature

#210 Automate created_at and updated_at DB fields
  database/init_db.go
  database/resource.sql
Labels: kind/feature

#215 sink lets database add created_at and update updated_at timestamps in resource table
  pkg/database/database.go
Labels: kind/feature

#209 Add instrumentation to the database
  cmd/api/routers/routers.go
  cmd/sink/main.go
  go.mod
  go.sum
  pkg/database/database.go
Labels: kind/feature

#205 Apply Helm naming conventions to general templates
  charts/kubearchive/templates/api_server/certificates.yaml
  charts/kubearchive/templates/certificates.yaml
Labels: kind/feature

#217 sink deletes k8s objects when json path returns a value
  charts/kubearchive/templates/sink/sink.yaml
  charts/kubearchive/values.yaml
  cmd/operator/internal/controller/kubearchiveconfig_controller.go
  cmd/sink/client.go
  cmd/sink/jsonPath/jsonPath.go
  cmd/sink/main.go
Labels: kind/feature

#244 Add new Role and RoleBinding for sink.
  cmd/operator/internal/controller/kubearchiveconfig_controller.go
Labels: kind/feature

#246 Enable 'go mod tidy' for renovate
  renovate.json
Labels: kind/feature

#235 Helm naming conventions docs
  README.md
  charts/kubearchive/templates/certificates.yaml
  docs/README.md
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/contributors/naming-conventions.adoc
Labels: kind/documentation

#211 Add required helm kw to api templates
  charts/kubearchive/templates/api_server/api_server.yaml
  charts/kubearchive/templates/api_server/certificates.yaml
Labels: kind/feature

#268 Fix docs header link
  docs/antora-playbook.yaml
Labels: kind/bug

#257 Operator creates and managers a filter ConfigMap
  cmd/operator/internal/controller/kubearchiveconfig_controller.go
  go.mod
Labels: kind/feature

#282 Fix integration tests
  test/integration/integration_test.go
Labels: kind/bug

#214 Add Jaeger deployment
  charts/kubearchive/templates/_helpers.tpl
  charts/kubearchive/templates/api_server/api_server.yaml
  charts/kubearchive/templates/sink/sink.yaml
  charts/kubearchive/templates/traces-collector.yaml
  charts/kubearchive/values.yaml
  go.mod
  go.sum
  pkg/observability/trace.go
Labels: kind/feature

#273 Set service name for telemetry
  cmd/api/main.go
  cmd/sink/main.go
  pkg/observability/trace.go
Labels: kind/bug

#281 Add instrumentation for HTTP client
  cmd/api/auth/authn.go
  cmd/api/auth/authz.go
  cmd/api/auth/authz_test.go
  cmd/api/discovery/apiresources.go
  cmd/api/discovery/apiresources_test.go
  cmd/api/main.go
Labels: kind/feature

#269 Extract DDL to its own file
  database/ddl.sql
  database/dml-example.sql
  database/init_db.go
  docs/modules/ROOT/pages/reference/database.adoc
  pkg/database/database.go
Labels: kind/feature

#248 Add kubectl-archive plugin with get command
  DEVELOPMENT.md
  cmd/kubectl-archive/main.go
  go.mod
  go.sum
  pkg/cmd/get.go
Labels: kind/feature

#265 sink does not try to delete k8s objects twice
  DEVELOPMENT.md
  cmd/operator/internal/controller/kubearchiveconfig_controller.go
  cmd/sink/main.go
  hack/quick-install.sh
Labels: kind/bug
