Repository kubearchive/kubearchive, pull requests merged in 2024-12, with the labels that each got.

#688 Replace os.Setenv with t.Setenv in the database environment tests
  pkg/database/environment_test.go
Labels: area/database, area/ci, size/extra-small

#683 Handle SIGTERM on the API
  cmd/api/main.go
Labels: kind/feature

#680 Add documentation style document
  cmd/operator/main.go
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/contributors/documentation.adoc
  docs/modules/ROOT/pages/contributors/release.adoc
  docs/modules/ROOT/pages/design/logging-integration.adoc
  docs/modules/ROOT/pages/getting-started/configuration.adoc
  docs/modules/ROOT/pages/integrations/logging.adoc
Labels: kind/feature

#674 Do not deserialize resources from the database
  charts/kubearchive/templates/api_server/api_server.yaml
  cmd/api/routers/routers.go
  cmd/api/routers/routers_test.go
  pkg/database/database.go
  pkg/database/database_test.go
  pkg/database/fake/database_generated.go
  pkg/database/fake/database_generated_test.go
Labels: kind/feature

#694 Merge API handlers
  cmd/api/main.go
  cmd/api/routers/routers.go
  cmd/api/routers/routers_test.go
  pkg/database/database.go
  pkg/database/database_test.go
  pkg/database/fake/database_generated.go
  pkg/database/fake/database_generated_test.go
Labels: component/api

#665 Sink mounts kubearchive-logging ConfigMap
  charts/kubearchive/templates/sink/sink.yaml
  cmd/sink/logs/logs.go
  cmd/sink/logs/logs_test.go
  cmd/sink/logs/testdata/emptyLoggingConfig/..gitkeep
  cmd/sink/logs/testdata/es/container-names/CONTAINER_NAME
  cmd/sink/logs/testdata/es/container-names/DATA_VIEW_ID
  cmd/sink/logs/testdata/es/container-names/LOG_URL
  cmd/sink/logs/testdata/es/container-names/POD_ID
  cmd/sink/logs/testdata/es/no-container-names/DATA_VIEW_ID
  cmd/sink/logs/testdata/es/no-container-names/LOG_URL
  cmd/sink/logs/testdata/es/no-container-names/POD_ID
  cmd/sink/logs/testdata/kubearchive-config-es.json
  cmd/sink/logs/testdata/kubearchive-config-splunk.json
  cmd/sink/logs/testdata/kubearchive-logging-es-container-name.json
  cmd/sink/logs/testdata/kubearchive-logging-es.json
  cmd/sink/logs/testdata/kubearchive-logging-splunk-container-name.json
  cmd/sink/logs/testdata/kubearchive-logging-splunk.json
  cmd/sink/logs/testdata/splunk-test1-urls.json
  cmd/sink/logs/testdata/splunk-test2-urls.json
  cmd/sink/logs/testdata/splunk/container-names/CONTAINER
  cmd/sink/logs/testdata/splunk/container-names/CONTAINER_NAME
  cmd/sink/logs/testdata/splunk/container-names/LOG_URL
  cmd/sink/logs/testdata/splunk/container-names/POD
  cmd/sink/logs/testdata/splunk/container-names/POD_ID
  cmd/sink/logs/testdata/splunk/no-container-names/CONTAINER
  cmd/sink/logs/testdata/splunk/no-container-names/LOG_URL
  cmd/sink/logs/testdata/splunk/no-container-names/POD
  cmd/sink/logs/testdata/splunk/no-container-names/POD_ID
  cmd/sink/main.go
  pkg/files/files.go
  pkg/files/files_test.go
  pkg/files/testdata/files/one
  pkg/files/testdata/files/three
  pkg/files/testdata/files/two
  pkg/files/testdata/filesWithDir/dir/.gitkeep
  pkg/files/testdata/filesWithDir/one
  pkg/files/testdata/filesWithDir/three
  pkg/files/testdata/filesWithDir/two
  pkg/files/testdata/filesWithDotDot/..one
  pkg/files/testdata/filesWithDotDot/..three
  pkg/files/testdata/filesWithDotDot/..two
  pkg/files/testdata/filesWithDotDot/one
  pkg/files/testdata/filesWithDotDot/three
  pkg/files/testdata/filesWithDotDot/two
  pkg/logurls/logurls.go
  test/integration/integration_test.go
Labels: component/sink

#707 add json_path to log_url table
  cmd/sink/logs/logs.go
  cmd/sink/main.go
  integrations/database/mariadb/kubearchive.sql
  integrations/database/postgresql/kubearchive.sql
  pkg/database/database.go
  pkg/database/facade/inserter.go
  pkg/database/fake/database_generated.go
  pkg/database/fake/database_generated_test.go
Labels: kind/feature

#717 update to golang.org/x/crypto v0.31.0
  go.mod
  go.sum
Labels: area/ci
