Repository kubearchive/kubearchive, pull requests merged in 2024-10, with the labels that each got.

#494 Fix if/else expression on the release workflow
  .github/workflows/release.yml
Labels: kind/bug

#495 Remove observability configuration files
  charts/kubearchive/conf/grafana-otelcol-config.yaml
  charts/kubearchive/conf/kubearchive-otelcol-config.yaml
Labels: kind/bug

#493 Add a script for deploy in debug mode
  DEVELOPMENT.md
  charts/kubearchive/templates/api_server/api_server.yaml
  charts/kubearchive/templates/operator/operator.yaml
  charts/kubearchive/templates/operator/service.yaml
  charts/kubearchive/values.yaml
  test/debug/debug-deploy.sh
  test/debug/patch-security-context.yaml
  test/debug/patch-service.yaml
Labels: kind/feature, area/deployment

#450 Use slog on KubeArchive
  cmd/api/abort/abort.go
  cmd/api/main.go
  cmd/operator/main.go
  cmd/sink/filters/filters.go
  cmd/sink/main.go
  go.mod
  pkg/database/database.go
  pkg/database/database_test.go
  pkg/middleware/logging.go
  test/main.go
Labels: kind/feature, component/sink

#508 Change Security Mailing List to Email
  docs/modules/ROOT/pages/contributors/guide.adoc
Labels: kind/bug

#511 Create indexes in the database
  docs/modules/ROOT/pages/reference/database.adoc
  integrations/database/postgresql/kubearchive.sql
Labels: kind/feature

#505 Instrument Operator base client
  cmd/operator/main.go
Labels: kind/feature

#503 Perform SAR with get or list
  cmd/api/auth/authz.go
  cmd/api/auth/authz_test.go
Labels: kind/bug

#522 Add Slack Channel and other communication info
  README.md
Labels: kind/documentation

#515 Fix MariaDB deployment script
  integrations/database/mariadb/install.sh
Labels: kind/bug

#525 Sink looks for global filters under the key kubearchive instead of _global
  cmd/sink/filters/filters.go
Labels: component/sink

#484 Add pagination support
  cmd/api/main.go
  cmd/api/main_test.go
  cmd/api/pagination/pagination.go
  cmd/api/routers/routers.go
  cmd/api/routers/routers_test.go
  go.mod
  integrations/database/postgresql/kubearchive.sql
  pkg/database/database.go
  pkg/database/database_test.go
  pkg/database/fake/database_generated.go
  pkg/database/fake/database_generated_test.go
  pkg/database/mariadb.go
  pkg/database/postgresql.go
Labels: kind/feature

#468 make sure existing filters update if CEL expressions change
  charts/kubearchive/templates/sink/role.yaml
  charts/kubearchive/templates/sink/role_binding.yaml
  charts/kubearchive/templates/sink/sink.yaml
  charts/kubearchive/values.yaml
  cmd/sink/filters/filters.go
  cmd/sink/filters/filters_test.go
  cmd/sink/k8s/client.go
  cmd/sink/main.go
  go.mod
  pkg/files/read.go
  pkg/files/update.go
Labels: kind/bug, component/sink

#559 Merged QueryCoreResources and QueryResources
  cmd/api/pagination/pagination.go
  cmd/api/routers/routers.go
  cmd/api/routers/routers_test.go
  pkg/database/database.go
  pkg/database/database_test.go
  pkg/database/fake/database_generated.go
  pkg/database/fake/database_generated_test.go
  pkg/database/mariadb.go
  pkg/database/postgresql.go
Labels: kind/feature, area/database, component/api

#565 Use the whole SAR spec as the key of the cache for authZ
  cmd/api/auth/authz.go
  cmd/api/auth/authz_test.go
Labels: kind/bug, component/api

#571 remove unused jsonPath code
  cmd/sink/jsonPath/jsonPath.go
Labels: component/sink

#573 Add host and runtime metrics
  charts/kubearchive/templates/api_server/api_server.yaml
  charts/kubearchive/templates/operator/operator.yaml
  charts/kubearchive/templates/sink/sink.yaml
  go.mod
  go.sum
  integrations/observability/grafana/resources.yaml
  pkg/observability/trace.go
Labels: kind/feature, area/metrics

#534 use environment variable to get the key for global filters
  charts/kubearchive/templates/sink/sink.yaml
  cmd/sink/filters/filters.go
Labels: component/sink

#560 Sink now applies global filters as well
  cmd/operator/api/v1alpha1/kubearchiveconfig_webhook.go
  cmd/sink/filters/filters.go
  cmd/sink/filters/filters_test.go
  cmd/sink/filters/testdata/cm.yaml
  cmd/sink/main.go
  pkg/cel/cel.go
Labels: kind/bug, component/sink

#516 Add documentation for global filters
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/configuration/global-filters.adoc
Labels: kind/documentation

#584 Improve PostgreSQL DB queries
  integrations/database/postgresql/kubearchive.sql
  pkg/database/postgresql.go
Labels: kind/feature, area/performance

#594 fix sink filter test setup
  cmd/sink/filters/filters_test.go
Labels: component/sink

#600 Add tests and docs for pagination
  cmd/api/pagination/pagination.go
  cmd/api/pagination/pagination_test.go
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/reference/api.adoc
  test/integration/integration_test.go
  test/main.go
Labels: kind/documentation, kind/bug

#576 Sink generates log urls for pods
  cmd/api/main_test.go
  cmd/api/routers/routers_test.go
  cmd/sink/logs/logs.go
  cmd/sink/logs/logs_test.go
  cmd/sink/logs/testdata/es-test1-urls.json
  cmd/sink/logs/testdata/es-test2-urls.json
  cmd/sink/logs/testdata/kubearchive-config-es.json
  cmd/sink/logs/testdata/kubearchive-config-splunk.json
  cmd/sink/logs/testdata/kubearchive-logging-es.json
  cmd/sink/logs/testdata/kubearchive-logging-splunk.json
  cmd/sink/logs/testdata/splunk-test1-urls.json
  cmd/sink/logs/testdata/splunk-test2-urls.json
  cmd/sink/logs/testdata/test1-data.json
  cmd/sink/logs/testdata/test2-data.json
  cmd/sink/main.go
  docs/modules/ROOT/pages/integrations/logging.adoc
  pkg/database/database.go
  pkg/database/fake/database_generated.go
  pkg/database/fake/database_generated_test.go
  pkg/database/mariadb.go
  pkg/database/postgresql.go
  pkg/log_urls/log_urls.go
Labels: kind/feature, component/sink
