Repository kubearchive/kubearchive, pull requests merged in 2025-07, with the labels that each got.

#1111 Add vector/loki integration
  .github/workflows/go_test_integration.yml
  integrations/logging/loki/README.md
  integrations/logging/loki/install.sh
  integrations/logging/loki/manifests/cluster-output.yaml
  integrations/logging/loki/patch-logging-secret.yaml
  integrations/logging/loki/uninstall.sh
  integrations/logging/loki/values.grafana.yaml
  integrations/logging/loki/values.loki.yaml
  integrations/logging/loki/values.minio.yaml
  integrations/logging/loki/values.vector.yaml
Labels: kind/feature, area/deployment, size/medium

#1125 add kafka integration
  DEVELOPMENT.md
  hack/quick-install.sh
  integrations/kafka/README.md
  integrations/kafka/config-br-defaults-kafka.yaml
  integrations/kafka/config-br-defaults.yaml
  integrations/kafka/install.sh
  integrations/kafka/kafka-broker-config.yaml
  integrations/kafka/uninstall.sh
Labels: kind/feature, area/deployment, size/small

#1178 Add output format on the cli - using kubectl approach
  go.mod
  pkg/cmd/get.go
  pkg/cmd/get_test.go
  pkg/cmd/testdata/expected_json_output.json
  pkg/cmd/testdata/expected_table_output.txt
  pkg/cmd/testdata/expected_yaml_output.yaml
Labels: kind/feature, component/cli, size/small

#1202 Add lease-duration flag
  cmd/operator/main.go
Labels: kind/feature, component/operator, size/extra-small

#1217 avoid updating Namespaces if not needed
  cmd/operator/internal/controller/kubearchiveconfig_controller.go
Labels: kind/bug, component/operator, size/extra-small

#1220 Fix the set up PR for external contributors
  .github/workflows/assign-reviewers.yml
  .github/workflows/copy-labels.yml
Labels: kind/bug, area/ci, size/extra-small

#1226 Improve documentation regarding kubearchive.cloudevents.total
  docs/modules/ROOT/pages/configuration/observability.adoc
Labels: kind/documentation, size/extra-small

#1231 Fix impersonation test state handling
  config/templates/api_server/api_server.yaml
  test/integration/impersonation_test.go
Labels: kind/bug, component/api, area/ci, size/extra-small

#1209 Reduce otelgin metrics series
  cmd/api/main.go
  cmd/sink/server/server.go
Labels: kind/bug, component/api, component/sink, size/extra-small
