Repository kubearchive/kubearchive, pull requests merged in 2025-02, with the labels that each got.

#794 Add decisions from the GDoc
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/design/decisions.adoc
Labels: kind/documentation

#793 Sink and API now fail on DB startup error
  pkg/database/connection.go
  pkg/database/database.go
Labels: kind/bug, component/api, component/sink, size/extra-small

#771 refactor sink to use gin http server
  cmd/sink/filters/fake/filters.go
  cmd/sink/filters/fake/filters_test.go
  cmd/sink/filters/filters.go
  cmd/sink/main.go
  cmd/sink/routers/routers.go
  cmd/sink/routers/routers_test.go
  cmd/sink/routers/testdata/CE-job-delete.json
  cmd/sink/routers/testdata/CE-job.json
  cmd/sink/routers/testdata/CE-pod-1-container-delete.json
  cmd/sink/routers/testdata/CE-pod-1-container.json
  cmd/sink/routers/testdata/CE-pod-3-container-delete.json
  cmd/sink/routers/testdata/CE-pod-3-container.json
  cmd/sink/routers/testdata/loggingconfig/LOG_URL
  cmd/sink/routers/testdata/loggingconfig/LOG_URL_JSONPATH
  cmd/sink/routers/testdata/loggingconfig/POD_ID
  cmd/sink/routers/testdata/not-CE.json
  cmd/sink/server/server.go
  integrations/observability/grafana/install.sh
  pkg/database/fake/database_generated.go
Labels: component/sink

#804 Introduce LOG_LEVEL and log changes
  cmd/api/main.go
  cmd/operator/main.go
  cmd/sink/main.go
  cmd/sink/server/server.go
  config/templates/api_server/api_server.yaml
  config/templates/operator/operator.yaml
  config/templates/sink/sink.yaml
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/configuration/kubearchive-logs.adoc
  pkg/logging/logging.go
  pkg/middleware/logging.go
Labels: kind/feature

#810 Fix timeout on splunk installation
  integrations/logging/splunk/install.sh
Labels: kind/bug

#776 Move logging integration test to its own func
  .github/workflows/go_test_integration.yml
  test/integration/database_test.go
  test/integration/integration_test.go
  test/integration/logging_test.go
  test/integration/pagination_test.go
  test/main.go
Labels: kind/bug, area/ci

#815 More explicit sink log messages
  cmd/sink/routers/routers.go
  config/templates/sink/sink.yaml
Labels: kind/feature, component/sink

#799 Logs can be sent to OTLP endpoint
  cmd/api/main.go
  cmd/operator/main.go
  cmd/sink/main.go
  config/templates/api_server/api_server.yaml
  config/templates/operator/operator.yaml
  config/templates/sink/sink.yaml
  docs/modules/ROOT/pages/configuration/enable-observability.adoc
  go.mod
  go.sum
  integrations/observability/grafana/install.sh
  integrations/observability/grafana/otel-collector-config.yaml
  pkg/observability/trace.go
Labels: kind/feature

#805 add liveness and readyness endpoints to the sink
  cmd/sink/routers/routers.go
  cmd/sink/routers/routers_test.go
  cmd/sink/server/server.go
  config/templates/sink/sink.yaml
Labels: kind/feature, component/sink

#808 Add database integration docs
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/getting-started/installation.adoc
  docs/modules/ROOT/pages/integrations/database.adoc
  integrations/database/postgresql/kubearchive.sql
  integrations/database/postgresql/postgres.yaml
Labels: kind/documentation

#849 Add ON DELETE CASCADE to log_url FK
  integrations/database/postgresql/kubearchive.sql
Labels: kind/bug, area/database

#811 sink sends proper http response based on processing of a cloud event
  cmd/sink/routers/result.go
  cmd/sink/routers/routers.go
  cmd/sink/routers/routers_test.go
  cmd/sink/routers/testdata/CE-not-k8s.json
  cmd/sink/routers/testdata/CE-pod-does-not-exist.json
  pkg/database/fake/database_generated.go
  pkg/database/fake/database_generated_test.go
Labels: kind/feature, component/sink, area/performance

#802 move shared router code to pkg
  cmd/api/auth/authn.go
  cmd/api/auth/authz.go
  cmd/api/discovery/apiresources.go
  cmd/api/logging/logging.go
  cmd/api/pagination/pagination.go
  cmd/api/routers/routers.go
  cmd/sink/routers/routers.go
  pkg/abort/abort.go
  pkg/observability/trace.go
Labels: component/api, area/metrics

#839 Change PostgreSQL timestamps to be 'with timezone'
  integrations/database/postgresql/kubearchive.sql
Labels: kind/feature

#844 Support empty KubeArchiveConfig.
  cmd/operator/internal/controller/kubearchiveconfig_controller.go
  test/integration/integration_test.go
  test/integration/logging_test.go
  test/integration/operator_test.go
  test/integration/pagination_test.go
  test/main.go
Labels: kind/bug, component/operator
