Repository kubearchive/kubearchive, pull requests merged in 2025-04, with the labels that each got.

#981 Add now() function for CEL expressions.
  pkg/cel/cel.go
  pkg/cel/cel_test.go
Labels: kind/feature

#963 Performance tests Locust CSV output
  test/performance/run.sh
Labels: area/ci

#923 Inequality filter
  docs/modules/ROOT/pages/design/database-interface.adoc
  docs/modules/ROOT/pages/integrations/database.adoc
  pkg/database/facade/filter.go
  pkg/database/mariadb.go
  pkg/database/postgresql.go
  pkg/database/reader.go
  pkg/database/reader_test.go
Labels: kind/feature

#935 Refactor DB package to segregate sql related code
  cmd/api/main.go
  cmd/api/routers/routers.go
  cmd/api/routers/routers_test.go
  cmd/sink/main.go
  cmd/sink/routers/routers.go
  cmd/sink/routers/routers_test.go
  docs/modules/ROOT/pages/design/database-interface.adoc
  docs/modules/ROOT/pages/integrations/database.adoc
  pkg/database/database.go
  pkg/database/env/environment.go
  pkg/database/env/environment_test.go
  pkg/database/errors/errors.go
  pkg/database/fake/database_generated.go
  pkg/database/fake/database_generated_test.go
  pkg/database/interfaces/database.go
  pkg/database/sql/connection.go
  pkg/database/sql/database.go
  pkg/database/sql/database_test.go
  pkg/database/sql/facade/creator.go
  pkg/database/sql/facade/deleter.go
  pkg/database/sql/facade/filter.go
  pkg/database/sql/facade/inserter.go
  pkg/database/sql/facade/selector.go
  pkg/database/sql/facade/sorter.go
  pkg/database/sql/mariadb.go
  pkg/database/sql/postgresql.go
  pkg/database/sql/query.go
  pkg/database/sql/reader.go
  pkg/database/sql/reader_test.go
  pkg/database/sql/writer.go
  pkg/database/sql/writer_test.go
  pkg/models/labels.go
Labels: kind/feature

#971 Update Eventing to avoid permissions requests
  .github/workflows/go_test_integration.yml
  .github/workflows/performance.yml
  docs/modules/ROOT/pages/getting-started/installation.adoc
  hack/quick-install.sh
Labels: kind/feature

#972 Workflow for setting up the PR
  .github/assign_label_reviewers.yml
  .github/issue_template.md
  .github/pull_request_template.md
  .github/workflows/assign-reviewers.yml
  .github/workflows/check-labels.yml
  .github/workflows/copy-labels.yml
  .github/workflows/release.yml
Labels: kind/feature, area/ci

#967 Add a test to check the order of retrieved logs
  test/integration/logging_test.go
  test/main.go
Labels: kind/feature

#993 Add Prometheus Operator as an integration
  integrations/observability/prometheus-operator/README.md
  integrations/observability/prometheus-operator/install.sh
  integrations/observability/prometheus-operator/kustomization.yaml
  integrations/observability/prometheus-operator/monitoring-otel-collector.yaml
  integrations/observability/prometheus-operator/monitoring-servicemonitor.yaml
  integrations/observability/prometheus-operator/otel-collector-config.yaml
Labels: kind/feature, area/ci

#1015 Replace sink-filters ConfigMap with a CRD.
  .gitignore
  cmd/operator/api/v1alpha1/clusterkubearchiveconfig_types.go
  cmd/operator/api/v1alpha1/clusterkubearchiveconfig_webhook.go
  cmd/operator/api/v1alpha1/kubearchiveconfig_types.go
  cmd/operator/api/v1alpha1/kubearchiveconfig_webhook.go
  cmd/operator/api/v1alpha1/sinkfilter_type.go
  cmd/operator/api/v1alpha1/sinkfilter_webhook.go
  cmd/operator/api/v1alpha1/sinkfilter_webhook_test.go
  cmd/operator/internal/controller/clusterkubearchiveconfig_controller.go
  cmd/operator/internal/controller/common.go
  cmd/operator/internal/controller/kubearchiveconfig_controller.go
  cmd/operator/main.go
  cmd/sink/filters/filters.go
  cmd/sink/filters/filters_test.go
  cmd/sink/filters/namespace_gvk.go
  cmd/sink/filters/testdata/cm.yaml
  cmd/sink/filters/testdata/sf.yaml
  cmd/sink/main.go
  cmd/sink/routers/routers.go
  cmd/sink/routers/routers_test.go
  config/kustomization.yaml
  config/templates/operator/webhooks.yaml
  config/templates/sink/role.yaml
  pkg/constants/constants.go
  test/integration/operator_test.go
  test/main.go
Labels: kind/feature, component/operator, component/sink

#1032 skip label, assignee, issue link CI actions for renovate PRs
  .github/workflows/assign-reviewers.yml
  .github/workflows/check-labels.yml
  .github/workflows/copy-labels.yml
Labels: kind/bug, area/ci, size/small

#1023 Added integration tests for labelSelector
  pkg/database/sql/postgresql.go
  pkg/models/labels.go
  test/integration/labels_test.go
Labels: kind/bug, component/api, size/extra-small

#945 Add rules for Release Notes
  .github/pull_request_template.md
  docs/modules/ROOT/pages/contributors/release.adoc
Labels: kind/feature

#907 Introduce SQL migrations
  .github/workflows/go_test_integration.yml
  DEVELOPMENT.md
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/configuration/upgrading.adoc
  docs/modules/ROOT/pages/design/database-migrations.adoc
  docs/modules/ROOT/pages/getting-started/installation.adoc
  integrations/database/postgresql/README.md
  integrations/database/postgresql/create-user.sql
  integrations/database/postgresql/install.sh
  integrations/database/postgresql/kubearchive-user.yaml
  integrations/database/postgresql/kubearchive.sql
  integrations/database/postgresql/migrations/01_initial_schema.down.sql
  integrations/database/postgresql/migrations/01_initial_schema.up.sql
  integrations/database/postgresql/postgres.yaml
  integrations/database/postgresql/setup.sql
  pkg/database/database.go
  pkg/database/fake/database_generated.go
  pkg/database/interfaces/database.go
  pkg/database/sql/database.go
  pkg/database/sql/facade/selector.go
Labels: kind/feature, area/database, size/medium

#1033 Add resources for vacuums.
  cmd/operator/internal/controller/clusterkubearchiveconfig_controller.go
  cmd/operator/internal/controller/common.go
  cmd/operator/internal/controller/kubearchiveconfig_controller.go
  cmd/operator/main.go
  config/kustomization.yaml
  config/templates/operator/cluster_role.yaml
  config/templates/operator/service_account.yaml
  config/templates/operator/sink_filters.yaml
  config/templates/sink/role.yaml
  pkg/constants/constants.go
  test/integration/operator_test.go
Labels: kind/feature

#1035 Add NamespaceVacuumConfig and ClusterVacuumConfig resources.
  cmd/operator/api/v1alpha1/clusterkubearchiveconfig_types.go
  cmd/operator/api/v1alpha1/clustervacuumconfig_types.go
  cmd/operator/api/v1alpha1/clustervacuumconfig_webhook.go
  cmd/operator/api/v1alpha1/clustervacuumconfig_webhook_test.go
  cmd/operator/api/v1alpha1/kubearchiveconfig_types.go
  cmd/operator/api/v1alpha1/namespacevacuumconfig_types.go
  cmd/operator/api/v1alpha1/namespacevacuumconfig_webhook.go
  cmd/operator/api/v1alpha1/namespacevacuumconfig_webhook_test.go
  cmd/operator/internal/controller/clusterkubearchiveconfig_controller.go
  cmd/operator/internal/controller/kubearchiveconfig_controller.go
  cmd/operator/main.go
  config/kustomization.yaml
  config/templates/operator/webhooks.yaml
Labels: kind/feature

#1025 Add sink cloudevent publisher.
  cmd/operator/api/v1alpha1/clusterkubearchiveconfig_types.go
  cmd/sink/k8s/client.go
  go.mod
  go.sum
  pkg/cloudevents/sink_publisher.go
Labels: kind/feature

#1043 Install migrate on performance tests
  .github/workflows/performance.yml
Labels: kind/feature, area/database, size/medium

#1003 Introduce custom metrics
  cmd/sink/routers/routers.go
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/configuration/enable-observability.adoc
  docs/modules/ROOT/pages/configuration/observability.adoc
  docs/modules/ROOT/pages/integrations/database.adoc
  go.mod
  integrations/observability/grafana/resources.yaml
  pkg/database/fake/database_generated.go
  pkg/database/fake/database_generated_test.go
  pkg/database/interfaces/database.go
  pkg/database/sql/mariadb.go
  pkg/database/sql/mariadb_test.go
  pkg/database/sql/postgresql.go
  pkg/database/sql/postgresql_test.go
  pkg/database/sql/query.go
  pkg/database/sql/writer.go
  pkg/database/sql/writer_test.go
  pkg/observability/metrics.go
  test/log-generators/pipelines/install.sh
Labels: kind/feature, area/metrics, size/medium

#1028 Fix empty log annotation use-case
  pkg/database/sql/reader.go
  test/integration/logging_test.go
Labels: kind/bug, component/api, size/extra-small

#1052 Add cluster and namespace vacuum documentation.
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/reference/vacuum.adoc
Labels: kind/feature

#1053 Fix vacuum documentation link.
  docs/modules/ROOT/nav.adoc
Labels: kind/feature

#1054 Fix vacuum link yet again.
  docs/modules/ROOT/nav.adoc
Labels: kind/feature

#1055 Fix context in bulleted list.
  docs/modules/ROOT/pages/reference/vacuum.adoc
Labels: kind/feature
