Repository kubearchive/kubearchive, pull requests merged in 2025-03, with the labels that each got.

#857 Introduced retries for performance requests
  test/performance/metrics/main.go
Labels: kind/bug, area/ci

#882 switch to linear backoffPolicy
  config/templates/eventing/brokers.yaml
Labels: area/deployment, area/performance

#874 Speed up integration test
  cmd/sink/routers/result.go
  cmd/sink/routers/routers.go
  cmd/sink/routers/routers_test.go
  test/integration/pagination_test.go
Labels: component/sink, area/ci

#879 Handle error when PR does not have kind
  hack/get-next-version.go
Labels: kind/bug

#904 remove deleteWhen so splunk correctly stores logs for pods with multiple containers
  test/integration/logging_test.go
Labels: kind/bug, area/ci

#911 Fix id value on sink log
  cmd/sink/routers/routers.go
Labels: kind/bug

#892 Add docs for testing Datadog logging integration
  DEVELOPMENT.md
  integrations/logging/datadog/README.md
  integrations/logging/datadog/app-key-instructions.png
  integrations/logging/datadog/datadog-agent.yaml
  integrations/logging/elasticsearch/README.md
  integrations/logging/splunk/README.md
Labels: kind/documentation

#918 integration test action should fail when go test cmd fails
  test/integration/run.sh
Labels: kind/bug, area/ci

#920 Add source information to logging
  pkg/logging/logging.go
Labels: kind/feature

#916 Increase the work_mem parameter from 4MB (default) to 64MB
  .editorconfig
  integrations/database/postgresql/kubearchive.sql
Labels: kind/feature

#946 Update label and annotation gin index
  integrations/database/postgresql/kubearchive.sql
Labels: kind/feature

#922 Fix GolangCI issues and schedule scan each month
  .github/workflows/golangci_lint.yml
  cmd/operator/internal/controller/kubearchiveconfig_controller.go
  cmd/sink/filters/filters.go
  cmd/sink/filters/filters_test.go
  pkg/cel/cel.go
Labels: area/ci

#937 Make resources not used outside its pkg unexported
  pkg/database/database.go
  pkg/database/database_test.go
  pkg/database/facade/filter.go
  pkg/database/facade/selector.go
  pkg/database/facade/sorter.go
  pkg/database/fake/database_generated.go
  pkg/database/fake/database_generated_test.go
  pkg/database/mariadb.go
  pkg/database/postgresql.go
Labels: kind/feature

#947 Update logging integration docs
  docs/modules/ROOT/pages/design/logging-integration.adoc
  docs/modules/ROOT/pages/integrations/logging.adoc
Labels: kind/documentation

#921 Refactor database to separate write and read functions
  cmd/api/main.go
  cmd/api/routers/routers.go
  cmd/api/routers/routers_test.go
  cmd/sink/main.go
  cmd/sink/routers/routers.go
  cmd/sink/routers/routers_test.go
  pkg/database/README.md
  pkg/database/database.go
  pkg/database/database_test.go
  pkg/database/mariadb.go
  pkg/database/postgresql.go
  pkg/database/reader.go
  pkg/database/reader_test.go
  pkg/database/writer.go
  pkg/database/writer_test.go
Labels: kind/feature

#962 Fix logic error in operator when reconciling the ServiceAccount.
  cmd/operator/internal/controller/kubearchiveconfig_controller.go
Labels: kind/bug, component/operator
