Repository kubearchive/kubearchive, pull requests merged in 2025-01, with the labels that each got.

#741 Fix timeout errors in integration tests
  .github/workflows/go_test_integration.yml
  cmd/api/logging/logging.go
  hack/quick-install.sh
  test/integration/integration_test.go
Labels: kind/bug, area/ci

#721 Database.WriteUrls does not transact with invalid arguments
  cmd/sink/main.go
  pkg/database/database.go
  pkg/database/fake/database_generated.go
  pkg/database/fake/database_generated_test.go
Labels: kind/bug, area/database

#756 Set sslmode as required for PostgreSQL
  docs/modules/ROOT/pages/getting-started/installation.adoc
  integrations/database/postgresql/postgres.yaml
  pkg/database/postgresql.go
Labels: kind/feature

#754 Fix integration test errors
  .github/workflows/go_test_integration.yml
  test/integration/integration_test.go
Labels: on-hold

#773 Integration tests improvements
  test/integration/integration_test.go
Labels: kind/bug, area/ci
