Repository kubearchive/kubearchive, pull requests merged in 2025-09, with the labels that each got.

#1343 Disable detected_level label in loki
  integrations/logging/loki/values.loki.yaml
  test/integration/logging_test.go
Labels: kind/bug, component/api, area/deployment, size/extra-small

#1324 Handle error when the broker has no URL
  pkg/cloudevents/sink_publisher.go
Labels: kind/bug, component/operator, size/small

#1327 Return 404 when resource do not exist
  cmd/api/discovery/apiresources.go
  cmd/api/discovery/apiresources_test.go
  cmd/api/main.go
  test/integration/integration_test.go
Labels: kind/bug, component/api, size/small

#1316 Introduce migration job
  config/kustomization.yaml
  config/templates/database/migration_job.yaml
  docs/modules/ROOT/pages/getting-started/installation.adoc
  hack/kubearchive-install.sh
  hack/release.sh
Labels: kind/feature, area/deployment, size/extra-small
